sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t dockerdev011/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true dockerdev011/react-test npm test

after_success: 
  - docker build -t dockerdev011/multi-client ./client
  - docker build -t dockerdev011/multi-nginx ./nginx
  - docker build -t dockerdev011/multi-server ./server
  - docker build -t dockerdev011/multi-worker ./worker 
  # Log in to the doker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub

  - docker push dockerdev011/multi-client
  - docker push dockerdev011/multi-nginx
  - docker push dockerdev011/multi-server
  - docker push dockerdev011/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multidocker-01
  env: Multidocker-01-env
  bucket_name: elasticbeanstalk-ap-southeast-2-365478768444
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
 